### PR TITLE
Tweak design

### PR DESCRIPTION
**Pull request by pareeohnos**
I've made a number of small design tweaks in preparation of a launch. It's a little rough around the edges as it was rushed to get it ready but hopefully this will do the job

### CODE REVIEW

**Comment by felixreynoso** [comment]
Hello @pareeohnos, thanks a lot for the PR. Will check it out right away!

**Comment by pareeohnos** [comment]
Awesome thanks. I've been told to go ahead and just deploy it when you've reviewed it but obviously I don't have access to do all that, but if you're happy with it all could you possibly get it deployed once merged?

**Comment by felixreynoso** [comment]
I checked it out and it looks awesome. Thanks for the help!!!

**Comment by felixreynoso** [comment]
Sure, I'll merge and deploy it right away.

**Comment by pareeohnos** [comment]
Ah no worries, thanks for getting it checked and deployed so fast 🙂

**Pull request merged**
